name: tinode
description: Implementation of Tinode SDK in dart.
version: 1.0.0
homepage: https://tinode.co/

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  rxdart: ^0.25.0
  web_socket_channel: ^1.1.0
  get_it: ^5.0.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
